apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.79
      helm:
        valueFiles:
          - $values/kubernetes/helm-values/dev/jenkins/values.yaml
    - repoURL: https://github.com/lmdevops/eks-devops-platform-template
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true